# -*- coding: utf-8 -*-
"""gunachatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qi1OgGRJG3O5MPQPY94UBHCKCbwf6E8R
"""

class HotelBookingChatbot:
    def __init__(self):
        self.hotels = {
            "Guna Green Farm": {"rooms": 15, "price": 130}
        }

    def show_hotels(self):
        print("Available hotels:")
        for hotel, details in self.hotels.items():
            print(f"{hotel} - ${details['price']} per night - {details['rooms']} rooms available")

    def book_hotel(self, hotel_name, rooms):
        if hotel_name in self.hotels:
            if self.hotels[hotel_name]["rooms"] >= rooms:
                self.hotels[hotel_name]["rooms"] -= rooms
                print(f"Booking confirmed! {rooms} room(s) booked at {hotel_name}.")
            else:
                print("Sorry, not enough rooms available.")
        else:
            print("Sorry, this hotel is not in our list.")

    def start(self):
        print("Welcome to the Guna Green Farm Booking Chatbot!")
        while True:
            print("\n1. View Resort Details\n2. Book a Room\n3. Exit")
            choice = input("Choose an option: ")

            if choice == "1":
                self.show_hotels()
            elif choice == "2":
                hotel_name = "Guna Green Farm"
                rooms = int(input("Enter number of rooms: "))
                self.book_hotel(hotel_name, rooms)
            elif choice == "3":
                print("Thank you for using the Guna Green Farm Booking Chatbot!")
                break
            else:
                print("Invalid option. Please try again.")

# Run the chatbot
chatbot = HotelBookingChatbot()
chatbot.start()